In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv')

In [4]:
print(df.head())

     id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  20

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              48895 non-null  int64  
 1   name                            48879 non-null  object 
 2   host_id                         48895 non-null  int64  
 3   host_name                       48874 non-null  object 
 4   neighbourhood_group             48895 non-null  object 
 5   neighbourhood                   48895 non-null  object 
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object 
 9   price                           48895 non-null  int64  
 10  minimum_nights                  48895 non-null  int64  
 11  number_of_reviews               48895 non-null  int64  
 12  last_review                     

In [6]:
df.describe()

id       host_id      latitude     longitude         price  \
count  4.889500e+04  4.889500e+04  48895.000000  48895.000000  48895.000000   
mean   1.901714e+07  6.762001e+07     40.728949    -73.952170    152.720687   
std    1.098311e+07  7.861097e+07      0.054530      0.046157    240.154170   
min    2.539000e+03  2.438000e+03     40.499790    -74.244420      0.000000   
25%    9.471945e+06  7.822033e+06     40.690100    -73.983070     69.000000   
50%    1.967728e+07  3.079382e+07     40.723070    -73.955680    106.000000   
75%    2.915218e+07  1.074344e+08     40.763115    -73.936275    175.000000   
max    3.648724e+07  2.743213e+08     40.913060    -73.712990  10000.000000   

       minimum_nights  number_of_reviews  reviews_per_month  \
count    48895.000000       48895.000000       38843.000000   
mean         7.029962          23.274466           1.373221   
std         20.510550          44.550582           1.680442   
min          1.000000           0.000000           0.010000   
25%          1.000000           1.000000           0.190000   
50%          3.000000           5.000000           0.720000   
75%          5.000000          24.000000           2.020000   
max       1250.000000         629.000000          58.500000   

       calculated_host_listings_count  availability_365  
count                    48895.000000      48895.000000  
mean                         7.143982        112.781327  
std                         32.952519        131.622289  
min                          1.000000          0.000000  
25%                          1.000000          0.000000  
50%                          1.000000         45.000000  
75%                          2.000000        227.000000  
max                        327.000000        365.000000

In [17]:
# 데이터의 각 host_name의 빈도수를 구하고 host_name으로 정렬하여 상위 5개를 출력하라

Ans = df.groupby('host_name').size()
print(Ans.head())

#Ans = df.value_counts().sort_index()
#print(Ans)

host_name
'Cil                        1
(Ari) HENRY LEE             1
(Email hidden by Airbnb)    6
(Mary) Haiy                 1
-TheQueensCornerLot         1
dtype: int64


In [83]:
# 데이터의 각 host_name의 빈도수를 구하고 빈도수 기준 내림차순 정렬한 데이터 프레임을 만들어라. 빈도수 컬럼은 counts로 명명하라
Ans = df['host_name'].value_counts().to_frame()
Ans.columns = ['counts']
Ans.sort_values('counts',ascending=False)

Ans = df.groupby('host_name').size().to_frame().rename(columns={0:'counts'}).sort_values('counts',ascending=False)

print(Ans)

              counts
host_name           
Michael          417
David            403
Sonder (NYC)     327
John             294
Alex             279
...              ...
Jerbean            1
Jerald             1
Jeonghoon          1
Jeny               1
현선                 1

[11452 rows x 1 columns]


In [92]:
# neighbourhood_group의 값에 따른 neighbourhood컬럼 값의 갯수를 구하여라

ans = df.groupby(['neighbourhood_group', 'neighbourhood'], as_index=False).size()

print(ans)

    neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]


In [98]:
# neighbourhood_group의 값에 따른 neighbourhood컬럼 값 중 neighbourhood_group그룹의 최댓값들을 출력하라

ans = df.groupby(['neighbourhood_group', 'neighbourhood']).size().groupby('neighbourhood_group').max()
print(ans)

KeyError: 'size'

In [136]:
# neighbourhood_group 값에 따른 price값의 평균, 분산, 최대, 최소 값을 구하여라
ans = df[['neighbourhood_group', 'price']].groupby('neighbourhood_group').agg(['mean','var','max','min'])
#ans = df[['neighbourhood_group', 'price']].groupby('neighbourhood_group').describe()
#

#ans = df.groupby('neighbourhood_group')['price'].agg(['mean','var','max','min'])
print(ans)

                          price                         
                           mean           var    max min
neighbourhood_group                                     
Bronx                 87.496792  11386.885081   2500   0
Brooklyn             124.383207  34921.719135  10000   0
Manhattan            196.875814  84904.159185  10000   0
Queens                99.517649  27923.130227  10000  10
Staten Island        114.812332  77073.088342   5000  13


In [137]:
# neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 구하라

ans = df.groupby(['neighbourhood', 'neighbourhood_group'])['price'].mean()
print(ans)

neighbourhood    neighbourhood_group
Allerton         Bronx                   87.595238
Arden Heights    Staten Island           67.250000
Arrochar         Staten Island          115.000000
Arverne          Queens                 171.779221
Astoria          Queens                 117.187778
                                           ...    
Windsor Terrace  Brooklyn               138.993631
Woodhaven        Queens                  67.170455
Woodlawn         Bronx                   60.090909
Woodrow          Staten Island          700.000000
Woodside         Queens                  85.097872
Name: price, Length: 221, dtype: float64


In [138]:
# neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하라

ans = df.groupby(['neighbourhood', 'neighbourhood_group'])['price'].mean().unstack()
print(ans)

neighbourhood_group      Bronx    Brooklyn  Manhattan      Queens  \
neighbourhood                                                       
Allerton             87.595238         NaN        NaN         NaN   
Arden Heights              NaN         NaN        NaN         NaN   
Arrochar                   NaN         NaN        NaN         NaN   
Arverne                    NaN         NaN        NaN  171.779221   
Astoria                    NaN         NaN        NaN  117.187778   
...                        ...         ...        ...         ...   
Windsor Terrace            NaN  138.993631        NaN         NaN   
Woodhaven                  NaN         NaN        NaN   67.170455   
Woodlawn             60.090909         NaN        NaN         NaN   
Woodrow                    NaN         NaN        NaN         NaN   
Woodside                   NaN         NaN        NaN   85.097872   

neighbourhood_group  Staten Island  
neighbourhood                       
Allerton                    

In [139]:
# neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하고 nan 값은 -999값으로 채워라

ans = df.groupby(['neighbourhood', 'neighbourhood_group'])['price'].mean().unstack().fillna(-999)
print(ans)

neighbourhood_group       Bronx    Brooklyn  Manhattan      Queens  \
neighbourhood                                                        
Allerton              87.595238 -999.000000     -999.0 -999.000000   
Arden Heights       -999.000000 -999.000000     -999.0 -999.000000   
Arrochar            -999.000000 -999.000000     -999.0 -999.000000   
Arverne             -999.000000 -999.000000     -999.0  171.779221   
Astoria             -999.000000 -999.000000     -999.0  117.187778   
...                         ...         ...        ...         ...   
Windsor Terrace     -999.000000  138.993631     -999.0 -999.000000   
Woodhaven           -999.000000 -999.000000     -999.0   67.170455   
Woodlawn              60.090909 -999.000000     -999.0 -999.000000   
Woodrow             -999.000000 -999.000000     -999.0 -999.000000   
Woodside            -999.000000 -999.000000     -999.0   85.097872   

neighbourhood_group  Staten Island  
neighbourhood                       
Allerton       

In [141]:
# 데이터중 neighbourhood_group 값이 Queens값을 가지는 데이터들 중 neighbourhood 그룹별로 price값의 평균, 분산, 최대, 최소값을 구하라

ans = df.loc[df['neighbourhood_group'] == 'Queens'].groupby('neighbourhood')['price'].agg(['mean', 'var', 'max', 'min'])

print(ans.head())

                     mean            var    max  min
neighbourhood                                       
Arverne        171.779221   37383.411141   1500   35
Astoria        117.187778  122428.811196  10000   25
Bay Terrace    142.000000    6816.400000    258   32
Bayside        157.948718  166106.470985   2600   30
Bayswater       87.470588    2330.889706    230   45


In [183]:
# 데이터중 neighbourhood_group 값에 따른 room_type 컬럼의 숫자를 구하고 neighbourhood_group 값을 기준으로 각 값의 비율을 구하여라
ans = df[['neighbourhood_group', 'room_type']].groupby(['neighbourhood_group','room_type']).size().unstack()
print(ans)
print(ans.values)
print(ans.sum(axis=1))
ans.loc[:,:] = (ans.values / ans.sum(axis=1).values.reshape(-1, 1))
print(ans)

room_type            Entire home/apt  Private room  Shared room
neighbourhood_group                                            
Bronx                            379           652           60
Brooklyn                        9559         10132          413
Manhattan                      13199          7982          480
Queens                          2096          3372          198
Staten Island                    176           188            9
[[  379   652    60]
 [ 9559 10132   413]
 [13199  7982   480]
 [ 2096  3372   198]
 [  176   188     9]]
neighbourhood_group
Bronx             1091
Brooklyn         20104
Manhattan        21661
Queens            5666
Staten Island      373
dtype: int64
room_type            Entire home/apt  Private room  Shared room
neighbourhood_group                                            
Bronx                       0.347388      0.597617     0.054995
Brooklyn                    0.475478      0.503979     0.020543
Manhattan                   0.609344      